name: docs

on:
  release:
    types:
      - published

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - run: |
          pip install \
          mkdocs-material \
          mkdocstrings[python]
      - run: mkdocs gh-deploy --force
