name: Code Stability

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: stability-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  stability:
    name: Code Stability
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build Python
        uses: ./.github/actions

      - name: Install tools
        run: poetry install --only dev

      - id: ruff
        if: always()
        run: make check-ruff

      - id: Black
        if: always()
        run: make check-black

      - id: mypy
        if: always()
        run: make check-mypy
